// Mocks generated by Mockito 5.4.6 from annotations
// in budmate/test/features/budget/domain/services/budget_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:budmate/core/errors.dart' as _i5;
import 'package:budmate/domain/budget_entity.dart' as _i6;
import 'package:budmate/domain/expense_entity.dart' as _i8;
import 'package:budmate/repositories/interfaces/budget_repository.dart' as _i3;
import 'package:budmate/repositories/interfaces/expense_repository.dart' as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BudgetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetRepository extends _i1.Mock implements _i3.BudgetRepository {
  MockBudgetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.BudgetEntity>> create(
    _i6.BudgetEntity? budget,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [budget]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.DatabaseFailure, _i6.BudgetEntity>
                >.value(
                  _FakeEither_0<_i5.DatabaseFailure, _i6.BudgetEntity>(
                    this,
                    Invocation.method(#create, [budget]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.BudgetEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, List<_i6.BudgetEntity>>> getAll(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.DatabaseFailure, List<_i6.BudgetEntity>>
                >.value(
                  _FakeEither_0<_i5.DatabaseFailure, List<_i6.BudgetEntity>>(
                    this,
                    Invocation.method(#getAll, [userId]),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.DatabaseFailure, List<_i6.BudgetEntity>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.BudgetEntity?>> getById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.DatabaseFailure, _i6.BudgetEntity?>
                >.value(
                  _FakeEither_0<_i5.DatabaseFailure, _i6.BudgetEntity?>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.BudgetEntity?>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.BudgetEntity>> update(
    _i6.BudgetEntity? budget,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [budget]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.DatabaseFailure, _i6.BudgetEntity>
                >.value(
                  _FakeEither_0<_i5.DatabaseFailure, _i6.BudgetEntity>(
                    this,
                    Invocation.method(#update, [budget]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.BudgetEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, void>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.DatabaseFailure, void>>.value(
                  _FakeEither_0<_i5.DatabaseFailure, void>(
                    this,
                    Invocation.method(#delete, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.DatabaseFailure, void>>);
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i7.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i8.ExpenseEntity>> create(
    _i8.ExpenseEntity? expense,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [expense]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.DatabaseFailure, _i8.ExpenseEntity>
                >.value(
                  _FakeEither_0<_i5.DatabaseFailure, _i8.ExpenseEntity>(
                    this,
                    Invocation.method(#create, [expense]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i8.ExpenseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>> getAll(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>
                >.value(
                  _FakeEither_0<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>(
                    this,
                    Invocation.method(#getAll, [userId]),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i8.ExpenseEntity?>> getById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.DatabaseFailure, _i8.ExpenseEntity?>
                >.value(
                  _FakeEither_0<_i5.DatabaseFailure, _i8.ExpenseEntity?>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i8.ExpenseEntity?>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>>
  getByCategory(String? userId, String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getByCategory, [userId, categoryId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>
                >.value(
                  _FakeEither_0<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>(
                    this,
                    Invocation.method(#getByCategory, [userId, categoryId]),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>>
  getByDateRange(String? userId, DateTime? startDate, DateTime? endDate) =>
      (super.noSuchMethod(
            Invocation.method(#getByDateRange, [userId, startDate, endDate]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>
                >.value(
                  _FakeEither_0<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>(
                    this,
                    Invocation.method(#getByDateRange, [
                      userId,
                      startDate,
                      endDate,
                    ]),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.DatabaseFailure, List<_i8.ExpenseEntity>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i8.ExpenseEntity>> update(
    _i8.ExpenseEntity? expense,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [expense]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.DatabaseFailure, _i8.ExpenseEntity>
                >.value(
                  _FakeEither_0<_i5.DatabaseFailure, _i8.ExpenseEntity>(
                    this,
                    Invocation.method(#update, [expense]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i8.ExpenseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, void>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.DatabaseFailure, void>>.value(
                  _FakeEither_0<_i5.DatabaseFailure, void>(
                    this,
                    Invocation.method(#delete, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.DatabaseFailure, void>>);
}
